# CNB 构建配置文件

# 定义构建流水线锚点
.pipeline: &pipeline
  runner:
    cpus: 64
  docker:
    image: node:18
  stages:
    # 检出代码
    - name: 检出代码
      script: |
        echo "检出 ${CNB_REPO} 仓库的 ${CNB_COMMIT} 提交"
        echo "分支: ${CNB_BRANCH}"
        
    # 安装项目依赖
    - name: 安装项目依赖
      script: |
        echo "安装Node.js依赖..."
        npm ci
        
    # 构建可执行文件
    - name: 构建跨平台可执行文件
      script: |
        echo "使用pkg构建Windows和Linux可执行文件..."
        npm run build
        
    # 显示构建结果
    - name: 显示构建产物
      script: |
        echo "构建完成，产物列表:"
        ls -la dist/

# 匹配main分支
main:
  push:
    - runner:
        cpus: 64
      docker:
        image: node:18
      stages:
        # 检出代码
        - name: 检出代码
          script: |
            echo "检出 ${CNB_REPO} 仓库的 ${CNB_COMMIT} 提交"
            echo "分支: ${CNB_BRANCH}"
            
        # 安装项目依赖
        - name: 安装项目依赖
          script: |
            echo "安装Node.js依赖..."
            npm ci || { echo "依赖安装失败"; exit 1; }
            
        # 构建可执行文件
        - name: 构建跨平台可执行文件
          script: |
            echo "使用pkg构建Windows和Linux可执行文件..."
            npm run build || { echo "构建失败"; exit 1; }
            
        # 显示构建结果
        - name: 显示构建产物
          script: |
            echo "构建完成，产物列表:"
            ls -la dist/ || { echo "没有找到dist目录"; exit 1; }
            
        # Git Release
        - name: git release
          type: git:release
          options:
            tag: ${CNB_BUILD_NUMBER}
            description: Beta release build ${CNB_BUILD_NUMBER} generated by CNB at $(date)
            
        # 上传构建产物
        - name: 上传构建产物
          type: cnbcool/attachments:latest
          options:
            tag: ${CNB_BUILD_NUMBER}
            assets: |
              dist/*

# 匹配master分支
master:
  push:
    - runner:
        cpus: 64
      docker:
        image: node:18
      stages:
        # 检出代码
        - name: 检出代码
          script: |
            echo "检出 ${CNB_REPO} 仓库的 ${CNB_COMMIT} 提交"
            echo "分支: ${CNB_BRANCH}"
            
        # 安装项目依赖
        - name: 安装项目依赖
          script: |
            echo "安装Node.js依赖..."
            npm ci || { echo "依赖安装失败"; exit 1; }
            
        # 构建可执行文件
        - name: 构建跨平台可执行文件
          script: |
            echo "使用pkg构建Windows和Linux可执行文件..."
            npm run build || { echo "构建失败"; exit 1; }
            
        # 显示构建结果
        - name: 显示构建产物
          script: |
            echo "构建完成，产物列表:"
            ls -la dist/ || { echo "没有找到dist目录"; exit 1; }
            
        # Git Release
        - name: git release
          type: git:release
          options:
            tag: v1.0.0-build.${CNB_BUILD_NUMBER}
            description: Beta release build ${CNB_BUILD_NUMBER} generated by CNB at $(date)
            
        # 上传构建产物
        - name: 上传构建产物
          type: cnbcool/attachments:latest
          options:
            tag: v1.0.0-build.${CNB_BUILD_NUMBER}
            assets: |
              dist/*