# CNB 构建配置文件

# 定义构建流水线锚点
.pipeline: &pipeline
  runner:
    cpus: 64
  docker:
    image: node:18
  stages:
    # 检出代码
    - name: 检出代码
      script: |
        echo "检出 ${CNB_REPO} 仓库的 ${CNB_COMMIT} 提交"
        echo "分支: ${CNB_BRANCH}"
        
    # 安装项目依赖
    - name: 安装项目依赖
      script: |
        echo "安装Node.js依赖..."
        npm ci
        
    # 构建可执行文件
    - name: 构建跨平台可执行文件
      script: |
        echo "使用pkg构建Windows和Linux可执行文件..."
        npm run build
        
    # 显示构建结果
    - name: 显示构建产物
      script: |
        echo "构建完成，产物列表:"
        ls -la dist/
      
    # 创建Release
    - name: 创建Release
      type: git:release
      options:
        title: release
        description: ${LATEST_CHANGE_LOG}
      
    # 上传构建产物到Release
    - name: 上传构建产物到Release
      image: cnbcool/attachments:latest
      settings:
        attachments:
          - dist/*

# 匹配main分支
main:
  push:
    - <<: *pipeline
# 匹配master分支
master:
  push:
    - <<: *pipeline