/**
 * 数据库建表
 * @param {string} dbType - 'postgres' | 'sqlite' | 'mysql'
 * @param {object} connection - 数据库连接
 */
async function createTables(dbType, connection) {
  switch (dbType.toLowerCase()) {
    case 'postgres':
    case 'postgresql':
      await connection.query(`CREATE TABLE IF NOT EXISTS products (id SERIAL PRIMARY KEY, name VARCHAR(255) NOT NULL, description TEXT, category VARCHAR(100), image_url VARCHAR(255), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)`);
      await connection.query(`CREATE TABLE IF NOT EXISTS news (id SERIAL PRIMARY KEY, title VARCHAR(255) NOT NULL, content TEXT, author VARCHAR(100), image_url VARCHAR(255), views INTEGER DEFAULT 0, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)`);
      await connection.query(`CREATE TABLE IF NOT EXISTS contact_messages (id SERIAL PRIMARY KEY, name VARCHAR(100) NOT NULL, email VARCHAR(255) NOT NULL, phone VARCHAR(20), message TEXT NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)`);
      await connection.query(`CREATE TABLE IF NOT EXISTS admins (id SERIAL PRIMARY KEY, username VARCHAR(50) UNIQUE NOT NULL, password VARCHAR(255) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)`);
      await connection.query(`CREATE TABLE IF NOT EXISTS users (id SERIAL PRIMARY KEY, phone VARCHAR(20) UNIQUE NOT NULL, email VARCHAR(255) UNIQUE NOT NULL, password VARCHAR(255) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)`);
      await connection.query(`CREATE TABLE IF NOT EXISTS goods (id SERIAL PRIMARY KEY, name VARCHAR(255) NOT NULL, price DECIMAL(10, 2) NOT NULL, currency VARCHAR(10) NOT NULL DEFAULT 'CNY', description TEXT, category VARCHAR(100), image_url VARCHAR(255), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)`);
      await connection.query(`CREATE TABLE IF NOT EXISTS site_config (id SERIAL PRIMARY KEY, company_name VARCHAR(255) NOT NULL, site_url VARCHAR(255) NOT NULL, icp_number VARCHAR(100), police_number VARCHAR(100), copyright_info TEXT, company_description TEXT, seo_keywords TEXT, site_title VARCHAR(255) NOT NULL, friend_links JSON, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)`);
      await connection.query(`CREATE TABLE IF NOT EXISTS categories (id SERIAL PRIMARY KEY, name VARCHAR(100) NOT NULL UNIQUE, description TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)`);
      // AI
      await connection.query(`CREATE TABLE IF NOT EXISTS ai_config (id SERIAL PRIMARY KEY, provider VARCHAR(50) NOT NULL DEFAULT 'openai', api_key VARCHAR(255), api_base_url VARCHAR(255) NOT NULL DEFAULT 'https://api.openai.com/v1', model VARCHAR(100) NOT NULL DEFAULT 'gpt-3.5-turbo', system_prompt TEXT, max_context_messages INTEGER DEFAULT 10, daily_global_limit INTEGER DEFAULT 100, retention_days INTEGER DEFAULT 30, enabled INTEGER DEFAULT 1, guest_allowed INTEGER DEFAULT 1, guest_daily_limit INTEGER DEFAULT 20, default_daily_limit INTEGER DEFAULT 50, default_monthly_limit INTEGER DEFAULT 500, default_total_limit INTEGER DEFAULT 0, temperature REAL DEFAULT 0.7, max_tokens INTEGER DEFAULT 2048, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)`);
      await connection.query(`CREATE TABLE IF NOT EXISTS ai_chat_sessions (id SERIAL PRIMARY KEY, user_id INTEGER NOT NULL, title VARCHAR(255), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)`);
      await connection.query(`CREATE TABLE IF NOT EXISTS ai_chat_messages (id SERIAL PRIMARY KEY, session_id INTEGER NOT NULL, user_id INTEGER NOT NULL, role VARCHAR(20) NOT NULL, content TEXT NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)`);
      await connection.query(`CREATE TABLE IF NOT EXISTS ai_user_quotas (id SERIAL PRIMARY KEY, user_id INTEGER NOT NULL UNIQUE, daily_limit INTEGER DEFAULT 50, monthly_limit INTEGER DEFAULT 500, total_limit INTEGER DEFAULT 0, used_today INTEGER DEFAULT 0, used_month INTEGER DEFAULT 0, used_total INTEGER DEFAULT 0, last_reset_date VARCHAR(10), last_reset_month VARCHAR(7), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)`);
      // Auth
      await connection.query(`CREATE TABLE IF NOT EXISTS admin_roles (id SERIAL PRIMARY KEY, name VARCHAR(100) UNIQUE NOT NULL, description TEXT DEFAULT '', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)`);
      await connection.query(`CREATE TABLE IF NOT EXISTS admin_permissions (id SERIAL PRIMARY KEY, code VARCHAR(100) UNIQUE NOT NULL, name VARCHAR(100) NOT NULL, description TEXT DEFAULT '', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)`);
      await connection.query(`CREATE TABLE IF NOT EXISTS admin_role_permissions (id SERIAL PRIMARY KEY, role_id INTEGER NOT NULL, permission_id INTEGER NOT NULL, UNIQUE(role_id, permission_id))`);
      await connection.query(`DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'admins' AND column_name = 'role_id') THEN ALTER TABLE admins ADD COLUMN role_id INTEGER; END IF; END $$;`);
      // Ticket
      await connection.query(`CREATE TABLE IF NOT EXISTS ticket_departments (id SERIAL PRIMARY KEY, name VARCHAR(100) UNIQUE NOT NULL, description TEXT DEFAULT '', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)`);
      await connection.query(`CREATE TABLE IF NOT EXISTS tickets (id SERIAL PRIMARY KEY, user_id INTEGER NOT NULL, department_id INTEGER NOT NULL, urgency VARCHAR(20) NOT NULL DEFAULT 'medium', urgency_order INTEGER NOT NULL DEFAULT 0, title VARCHAR(255) NOT NULL, content TEXT NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'pending', assigned_admin_id INTEGER, closed_by VARCHAR(20), closed_at TIMESTAMP, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)`);
      await connection.query(`CREATE TABLE IF NOT EXISTS ticket_replies (id SERIAL PRIMARY KEY, ticket_id INTEGER NOT NULL, user_id INTEGER, admin_id INTEGER, content TEXT NOT NULL, reply_type VARCHAR(10) NOT NULL DEFAULT 'user', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)`);
      await connection.query(`CREATE TABLE IF NOT EXISTS ticket_transfers (id SERIAL PRIMARY KEY, ticket_id INTEGER NOT NULL, from_department_id INTEGER, to_department_id INTEGER, from_admin_id INTEGER NOT NULL, to_admin_id INTEGER, reason TEXT DEFAULT '', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)`);
      await connection.query(`CREATE TABLE IF NOT EXISTS admin_departments (id SERIAL PRIMARY KEY, admin_id INTEGER NOT NULL, department_id INTEGER NOT NULL, UNIQUE(admin_id, department_id))`);
      break;

    case 'sqlite':
      await connection.asyncRun(`CREATE TABLE IF NOT EXISTS products (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, description TEXT, category TEXT, image_url TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP)`);
      await connection.asyncRun(`CREATE TABLE IF NOT EXISTS news (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL, content TEXT, author TEXT, image_url TEXT, views INTEGER DEFAULT 0, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP)`);
      await connection.asyncRun(`CREATE TABLE IF NOT EXISTS contact_messages (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, email TEXT NOT NULL, phone TEXT, message TEXT NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP)`);
      await connection.asyncRun(`CREATE TABLE IF NOT EXISTS admins (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT UNIQUE NOT NULL, password TEXT NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP)`);
      await connection.asyncRun(`CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, phone TEXT UNIQUE NOT NULL, email TEXT UNIQUE NOT NULL, password TEXT NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP)`);
      await connection.asyncRun(`CREATE TABLE IF NOT EXISTS goods (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, price REAL NOT NULL, currency TEXT NOT NULL DEFAULT 'CNY', description TEXT, category TEXT, image_url TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP)`);
      await connection.asyncRun(`CREATE TABLE IF NOT EXISTS site_config (id INTEGER PRIMARY KEY AUTOINCREMENT, company_name TEXT NOT NULL, site_url TEXT NOT NULL, icp_number TEXT, police_number TEXT, copyright_info TEXT, company_description TEXT, seo_keywords TEXT, site_title TEXT NOT NULL, friend_links TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP)`);
      await connection.asyncRun(`CREATE TABLE IF NOT EXISTS categories (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL UNIQUE, description TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP)`);
      // AI
      await connection.asyncRun(`CREATE TABLE IF NOT EXISTS ai_config (id INTEGER PRIMARY KEY AUTOINCREMENT, provider TEXT NOT NULL DEFAULT 'openai', api_key TEXT, api_base_url TEXT NOT NULL DEFAULT 'https://api.openai.com/v1', model TEXT NOT NULL DEFAULT 'gpt-3.5-turbo', system_prompt TEXT, max_context_messages INTEGER DEFAULT 10, daily_global_limit INTEGER DEFAULT 100, retention_days INTEGER DEFAULT 30, enabled INTEGER DEFAULT 1, guest_allowed INTEGER DEFAULT 1, guest_daily_limit INTEGER DEFAULT 20, default_daily_limit INTEGER DEFAULT 50, default_monthly_limit INTEGER DEFAULT 500, default_total_limit INTEGER DEFAULT 0, temperature REAL DEFAULT 0.7, max_tokens INTEGER DEFAULT 2048, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP)`);
      await connection.asyncRun(`CREATE TABLE IF NOT EXISTS ai_chat_sessions (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, title TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP)`);
      await connection.asyncRun(`CREATE TABLE IF NOT EXISTS ai_chat_messages (id INTEGER PRIMARY KEY AUTOINCREMENT, session_id INTEGER NOT NULL, user_id INTEGER NOT NULL, role TEXT NOT NULL, content TEXT NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP)`);
      await connection.asyncRun(`CREATE TABLE IF NOT EXISTS ai_user_quotas (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL UNIQUE, daily_limit INTEGER DEFAULT 50, monthly_limit INTEGER DEFAULT 500, total_limit INTEGER DEFAULT 0, used_today INTEGER DEFAULT 0, used_month INTEGER DEFAULT 0, used_total INTEGER DEFAULT 0, last_reset_date TEXT, last_reset_month TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP)`);
      // Auth
      await connection.asyncRun(`CREATE TABLE IF NOT EXISTS admin_roles (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT UNIQUE NOT NULL, description TEXT DEFAULT '', created_at DATETIME DEFAULT CURRENT_TIMESTAMP)`);
      await connection.asyncRun(`CREATE TABLE IF NOT EXISTS admin_permissions (id INTEGER PRIMARY KEY AUTOINCREMENT, code TEXT UNIQUE NOT NULL, name TEXT NOT NULL, description TEXT DEFAULT '', created_at DATETIME DEFAULT CURRENT_TIMESTAMP)`);
      await connection.asyncRun(`CREATE TABLE IF NOT EXISTS admin_role_permissions (id INTEGER PRIMARY KEY AUTOINCREMENT, role_id INTEGER NOT NULL, permission_id INTEGER NOT NULL, UNIQUE(role_id, permission_id))`);
      try { await connection.asyncRun('ALTER TABLE admins ADD COLUMN role_id INTEGER'); } catch (e) { /* 已存在则忽略 */ }
      // Ticket
      await connection.asyncRun(`CREATE TABLE IF NOT EXISTS ticket_departments (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT UNIQUE NOT NULL, description TEXT DEFAULT '', created_at DATETIME DEFAULT CURRENT_TIMESTAMP)`);
      await connection.asyncRun(`CREATE TABLE IF NOT EXISTS tickets (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, department_id INTEGER NOT NULL, urgency TEXT NOT NULL DEFAULT 'medium', urgency_order INTEGER NOT NULL DEFAULT 0, title TEXT NOT NULL, content TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'pending', assigned_admin_id INTEGER, closed_by TEXT, closed_at DATETIME, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP)`);
      await connection.asyncRun(`CREATE TABLE IF NOT EXISTS ticket_replies (id INTEGER PRIMARY KEY AUTOINCREMENT, ticket_id INTEGER NOT NULL, user_id INTEGER, admin_id INTEGER, content TEXT NOT NULL, reply_type TEXT NOT NULL DEFAULT 'user', created_at DATETIME DEFAULT CURRENT_TIMESTAMP)`);
      await connection.asyncRun(`CREATE TABLE IF NOT EXISTS ticket_transfers (id INTEGER PRIMARY KEY AUTOINCREMENT, ticket_id INTEGER NOT NULL, from_department_id INTEGER, to_department_id INTEGER, from_admin_id INTEGER NOT NULL, to_admin_id INTEGER, reason TEXT DEFAULT '', created_at DATETIME DEFAULT CURRENT_TIMESTAMP)`);
      await connection.asyncRun(`CREATE TABLE IF NOT EXISTS admin_departments (id INTEGER PRIMARY KEY AUTOINCREMENT, admin_id INTEGER NOT NULL, department_id INTEGER NOT NULL, UNIQUE(admin_id, department_id))`);
      break;

    case 'mysql':
    default:
      await connection.execute(`CREATE TABLE IF NOT EXISTS products (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255) NOT NULL, description TEXT, category VARCHAR(100), image_url VARCHAR(255), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)`);
      await connection.execute(`CREATE TABLE IF NOT EXISTS news (id INT AUTO_INCREMENT PRIMARY KEY, title VARCHAR(255) NOT NULL, content TEXT, author VARCHAR(100), image_url VARCHAR(255), views INT DEFAULT 0, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)`);
      await connection.execute(`CREATE TABLE IF NOT EXISTS contact_messages (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL, email VARCHAR(255) NOT NULL, phone VARCHAR(20), message TEXT NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)`);
      await connection.execute(`CREATE TABLE IF NOT EXISTS admins (id INT AUTO_INCREMENT PRIMARY KEY, username VARCHAR(50) UNIQUE NOT NULL, password VARCHAR(255) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)`);
      await connection.execute(`CREATE TABLE IF NOT EXISTS users (id INT AUTO_INCREMENT PRIMARY KEY, phone VARCHAR(20) UNIQUE NOT NULL, email VARCHAR(255) UNIQUE NOT NULL, password VARCHAR(255) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)`);
      await connection.execute(`CREATE TABLE IF NOT EXISTS goods (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255) NOT NULL, price DECIMAL(10, 2) NOT NULL, currency VARCHAR(10) NOT NULL DEFAULT 'CNY', description TEXT, category VARCHAR(100), image_url VARCHAR(255), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)`);
      await connection.execute(`CREATE TABLE IF NOT EXISTS site_config (id INT AUTO_INCREMENT PRIMARY KEY, company_name VARCHAR(255) NOT NULL, site_url VARCHAR(255) NOT NULL, icp_number VARCHAR(100), police_number VARCHAR(100), copyright_info TEXT, company_description TEXT, seo_keywords TEXT, site_title VARCHAR(255) NOT NULL, friend_links JSON, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)`);
      await connection.execute(`CREATE TABLE IF NOT EXISTS categories (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL UNIQUE, description TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)`);
      // AI
      await connection.execute(`CREATE TABLE IF NOT EXISTS ai_config (id INT AUTO_INCREMENT PRIMARY KEY, provider VARCHAR(50) NOT NULL DEFAULT 'openai', api_key VARCHAR(255), api_base_url VARCHAR(255) NOT NULL DEFAULT 'https://api.openai.com/v1', model VARCHAR(100) NOT NULL DEFAULT 'gpt-3.5-turbo', system_prompt TEXT, max_context_messages INT DEFAULT 10, daily_global_limit INT DEFAULT 100, retention_days INT DEFAULT 30, enabled INT DEFAULT 1, guest_allowed INT DEFAULT 1, guest_daily_limit INT DEFAULT 20, default_daily_limit INT DEFAULT 50, default_monthly_limit INT DEFAULT 500, default_total_limit INT DEFAULT 0, temperature FLOAT DEFAULT 0.7, max_tokens INT DEFAULT 2048, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)`);
      await connection.execute(`CREATE TABLE IF NOT EXISTS ai_chat_sessions (id INT AUTO_INCREMENT PRIMARY KEY, user_id INT NOT NULL, title VARCHAR(255), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)`);
      await connection.execute(`CREATE TABLE IF NOT EXISTS ai_chat_messages (id INT AUTO_INCREMENT PRIMARY KEY, session_id INT NOT NULL, user_id INT NOT NULL, role VARCHAR(20) NOT NULL, content TEXT NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)`);
      await connection.execute(`CREATE TABLE IF NOT EXISTS ai_user_quotas (id INT AUTO_INCREMENT PRIMARY KEY, user_id INT NOT NULL UNIQUE, daily_limit INT DEFAULT 50, monthly_limit INT DEFAULT 500, total_limit INT DEFAULT 0, used_today INT DEFAULT 0, used_month INT DEFAULT 0, used_total INT DEFAULT 0, last_reset_date VARCHAR(10), last_reset_month VARCHAR(7), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)`);
      // Auth
      await connection.execute(`CREATE TABLE IF NOT EXISTS admin_roles (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) UNIQUE NOT NULL, description TEXT DEFAULT '', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)`);
      await connection.execute(`CREATE TABLE IF NOT EXISTS admin_permissions (id INT AUTO_INCREMENT PRIMARY KEY, code VARCHAR(100) UNIQUE NOT NULL, name VARCHAR(100) NOT NULL, description TEXT DEFAULT '', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)`);
      await connection.execute(`CREATE TABLE IF NOT EXISTS admin_role_permissions (id INT AUTO_INCREMENT PRIMARY KEY, role_id INT NOT NULL, permission_id INT NOT NULL, UNIQUE KEY unique_role_permission (role_id, permission_id))`);
      await connection.execute(`CREATE PROCEDURE IF NOT EXISTS add_role_id_column() BEGIN IF NOT EXISTS (SELECT * FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'admins' AND column_name = 'role_id') THEN ALTER TABLE admins ADD COLUMN role_id INT; END IF; END`);
      await connection.execute('CALL add_role_id_column()');
      await connection.execute('DROP PROCEDURE IF EXISTS add_role_id_column');
      // Ticket
      await connection.execute(`CREATE TABLE IF NOT EXISTS ticket_departments (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) UNIQUE NOT NULL, description TEXT DEFAULT '', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)`);
      await connection.execute(`CREATE TABLE IF NOT EXISTS tickets (id INT AUTO_INCREMENT PRIMARY KEY, user_id INT NOT NULL, department_id INT NOT NULL, urgency VARCHAR(20) NOT NULL DEFAULT 'medium', urgency_order INT NOT NULL DEFAULT 0, title VARCHAR(255) NOT NULL, content TEXT NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'pending', assigned_admin_id INT, closed_by VARCHAR(20), closed_at TIMESTAMP NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)`);
      await connection.execute(`CREATE TABLE IF NOT EXISTS ticket_replies (id INT AUTO_INCREMENT PRIMARY KEY, ticket_id INT NOT NULL, user_id INT, admin_id INT, content TEXT NOT NULL, reply_type VARCHAR(10) NOT NULL DEFAULT 'user', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)`);
      await connection.execute(`CREATE TABLE IF NOT EXISTS ticket_transfers (id INT AUTO_INCREMENT PRIMARY KEY, ticket_id INT NOT NULL, from_department_id INT, to_department_id INT, from_admin_id INT NOT NULL, to_admin_id INT, reason TEXT DEFAULT '', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)`);
      await connection.execute(`CREATE TABLE IF NOT EXISTS admin_departments (id INT AUTO_INCREMENT PRIMARY KEY, admin_id INT NOT NULL, department_id INT NOT NULL, UNIQUE KEY unique_admin_dept (admin_id, department_id))`);
      break;
  }
}

module.exports = { createTables };
